# Generated by Django 5.2.5 on 2025-10-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('status', models.CharField(choices=[('Safe', 'Safe'), ('Phishing', 'Phishing')], max_length=10)),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
