# Generated by Django 5.2.5 on 2025-10-06 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_urlscan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlscan',
            old_name='scan_date',
            new_name='scan_days',
        ),
    ]
