# Generated by Django 5.2.5 on 2025-10-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_rename_scan_date_urlscan_scan_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlscan',
            name='threat_scores',
            field=models.IntegerField(default=0),
        ),
    ]
