# Generated by Django 5.2.5 on 2025-10-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0005_datasetupload_uploadfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.CharField(max_length=255, unique=True)),
                ('subject', models.TextField(blank=True, null=True)),
                ('sender', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
