# Generated by Django 5.2.5 on 2025-11-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0006_processedemail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasetupload',
            old_name='suspiicious',
            new_name='suspicious',
        ),
        migrations.AddField(
            model_name='processedemail',
            name='blacklist_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='processedemail',
            name='blacklist_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='processedemail',
            name='threat_score',
            field=models.FloatField(default=0.0),
        ),
    ]
