# Generated by Django 5.2.5 on 2025-11-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0007_rename_suspiicious_datasetupload_suspicious_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedemail',
            name='has_urls',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='processedemail',
            name='is_phishing',
            field=models.BooleanField(default=False),
        ),
    ]
