# Generated by Django 5.2.5 on 2025-11-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0008_processedemail_has_urls_processedemail_is_phishing'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedemail',
            name='urls_data',
            field=models.JSONField(default=list),
        ),
    ]
