# Generated by Django 5.2.5 on 2025-11-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0009_processedemail_urls_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='file',
        ),
        migrations.RemoveField(
            model_name='uploadfile',
            name='upload_at',
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='extracted_urls',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='file_hash',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='file_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='file_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='is_phishing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='mime_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='results',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='scanned_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
