# Generated by Django 5.2.5 on 2025-11-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0010_remove_uploadfile_file_remove_uploadfile_upload_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlscan',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=True),
            preserve_default=False,
        ),
    ]
