# Generated by Django 5.2.5 on 2025-11-20 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0011_urlscan_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiedScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('URL', 'Manual URL Scanner'), ('EMAIL', 'Email Scanner'), ('ATTACHMENT', 'Attachment Scanner')], max_length=20)),
                ('item', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=20)),
                ('detail_id', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('scanned_url', models.CharField(max_length=500)),
            ],
        ),
    ]
